In [40]:
import pandas as pd
df=pd.read_csv("messy_sales_dataset.csv")
df

,CustomerID,Name,Age,Gender,Country,Sales,OrderDate,Product,Quantity,Discount
0,CUST1000,MARY,30,male,NaN,NaN,March 3 2023,Tablet,NaN,NaN
1,CUST1001,Mary,NaN,male,NaN,100.5,NaN,phone,five,NaN
2,CUST1002,JOHN,35,female,INDIA,200.75,NaN,PHONE,NaN,5 percent
3,CUST1003,MARY,NaN,Male,NaN,200.75,2023-01-01,Tablet,2,5 percent
4,CUST1004,mary,unknown,NaN,INDIA,100.5,2023-01-01,Tablet,3,10%
...,...,...,...,...,...,...,...,...,...,...
1245,CUST1342,John,25,NaN,USA,100.5,01/02/2023,laptop,NaN,5 percent
1246,CUST1354,John,NaN,female,india,200.75,NaN,Tablet,five,5 percent
1247,CUST1023,JOHN,unknown,NaN,india,200.75,2023-01-01,Laptop,1,0.2
1248,CUST1043,ALEX,30,female,usa,100.5,01/02/2023,phone,2,NaN
1249,CUST1243,alex,40,Male,india,NaN,March 3 2023,laptop,2,5 percent

In [41]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
CustomerID      0
Name            0
Age           226
Gender        247
Country       217
Sales         214
OrderDate     317
Product         0
Quantity      265
Discount      315
dtype: int64

In [ ]:
# This show how many missing values exist in each column

In [42]:
df = df.dropna(subset='Sales')

In [43]:
df

,CustomerID,Name,Age,Gender,Country,Sales,OrderDate,Product,Quantity,Discount
1,CUST1001,Mary,NaN,male,NaN,100.5,NaN,phone,five,NaN
2,CUST1002,JOHN,35,female,INDIA,200.75,NaN,PHONE,NaN,5 percent
3,CUST1003,MARY,NaN,Male,NaN,200.75,2023-01-01,Tablet,2,5 percent
4,CUST1004,mary,unknown,NaN,INDIA,100.5,2023-01-01,Tablet,3,10%
5,CUST1005,MARY,40,Male,NaN,invalid,01/02/2023,phone,NaN,10%
...,...,...,...,...,...,...,...,...,...,...
1243,CUST1355,Mary,unknown,male,usa,100.5,2023-01-01,Tablet,3,10%
1245,CUST1342,John,25,NaN,USA,100.5,01/02/2023,laptop,NaN,5 percent
1246,CUST1354,John,NaN,female,india,200.75,NaN,Tablet,five,5 percent
1247,CUST1023,JOHN,unknown,NaN,india,200.75,2023-01-01,Laptop,1,0.2
1248,CUST1043,ALEX,30,female,usa,100.5,01/02/2023,phone,2,NaN

In [ ]:
#Drop the row where the key column is missing or null because they cannot be reliably used in analysis

In [44]:
df['Gender'].fillna("Unknown")

1          male
2        female
3          Male
4       Unknown
5          Male
         ...
1243       male
1245    Unknown
1246     female
1247    Unknown
1248     female
Name: Gender, Length: 1036, dtype: object

In [ ]:
#Missing values are filled  to avoid losing of data

In [55]:
df.drop_duplicates()

,CustomerID,Name,Age,Gender,Country,Sales,OrderDate,Product,Quantity,Discount
1,CUST1001,Mary,NaN,male,NaN,100.50,NaN,phone,five,NaN
2,CUST1002,JOHN,35.0,female,INDIA,200.75,NaN,PHONE,NaN,5 percent
3,CUST1003,MARY,NaN,Male,NaN,200.75,2023-01-01,Tablet,2,5 percent
4,CUST1004,mary,NaN,NaN,INDIA,100.50,2023-01-01,Tablet,3,10%
5,CUST1005,MARY,40.0,Male,NaN,NaN,01/02/2023,phone,NaN,10%
...,...,...,...,...,...,...,...,...,...,...
1195,CUST2195,mary,40.0,female,INDIA,200.75,NaN,laptop,NaN,NaN
1196,CUST2196,alex,35.0,NaN,usa,NaN,NaN,PHONE,1,0.2
1197,CUST2197,MARY,40.0,male,NaN,200.75,01/02/2023,phone,1,5 percent
1198,CUST2198,mary,30.0,Male,usa,200.75,NaN,laptop,3,0.2
1199,CUST2199,john,NaN,Male,india,NaN,2023-01-01,PHONE,2,0.2

In [62]:
#Duplicate rows were removed to prevent double counting and incorrect analysis

In [63]:
df["OrderDate"]=pd.to_datetime(df['OrderDate'], errors='coerce')
df.dtypes

/tmp/ipykernel_1030/4085279782.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["OrderDate"]=pd.to_datetime(df['OrderDate'], errors='coerce')

CustomerID            object
Name                  object
Age                  float64
Gender                object
Country               object
Sales                float64
OrderDate     datetime64[ns]
Product               object
Quantity              object
Discount              object
dtype: object

In [ ]:
#Datatype was corrected to ensure proper calculation and analysis