In [1]:
import pandas as pd

In [13]:
df=pd.read_csv("sales_day16.csv")
df

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
0     O0001  27/10/23   East       C001      P008         7        653
1     O0002  25/01/23  North       C008      P010         6        690
2     O0003  29/11/24   West       C008      P006         7        433
3     O0004  21/03/24   West       C009      P008         4        984
4     O0005  22/01/23  South       C020      P002         2        850
..      ...       ...    ...        ...       ...       ...        ...
295   O0296  28/07/24  South       C018      P006         7        497
296   O0297  31/01/24  South       C012      P007         1        647
297   O0298  28/10/24  South       C011      P001         9        296
298   O0299  27/03/23   West       C002      P006         2        763
299   O0300  22/11/23   East       C017      P006         4        124

[300 rows x 7 columns]

In [7]:
df.shape

(300, 7)

In [8]:
df.head()

  OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
0   O0001  27/10/23   East       C001      P008         7        653
1   O0002  25/01/23  North       C008      P010         6        690
2   O0003  29/11/24   West       C008      P006         7        433
3   O0004  21/03/24   West       C009      P008         4        984
4   O0005  22/01/23  South       C020      P002         2        850

In [9]:
df.tail()

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
295   O0296  28/07/24  South       C018      P006         7        497
296   O0297  31/01/24  South       C012      P007         1        647
297   O0298  28/10/24  South       C011      P001         9        296
298   O0299  27/03/23   West       C002      P006         2        763
299   O0300  22/11/23   East       C017      P006         4        124

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     300 non-null    object
 1   OrderDate   300 non-null    object
 2   Region      300 non-null    object
 3   CustomerID  300 non-null    object
 4   ProductID   300 non-null    object
 5   Quantity    300 non-null    int64
 6   UnitPrice   300 non-null    int64
dtypes: int64(2), object(5)
memory usage: 16.5+ KB

In [11]:
df.describe()

         Quantity   UnitPrice
count  300.000000  300.000000
mean     5.483333  555.370000
std      2.902494  264.949304
min      1.000000  110.000000
25%      3.000000  311.000000
50%      5.000000  576.500000
75%      8.000000  776.250000
max     10.000000  998.000000

In [14]:
# how many rows
df.shape[0]

300

In [16]:
# how many columns
df.shape[1]

7

In [19]:
# missing values
df.isnull().sum()

OrderID       0
OrderDate     0
Region        0
CustomerID    0
ProductID     0
Quantity      0
UnitPrice     0
dtype: int64

In [20]:
# average value
df["UnitPrice"].mean()

555.37