In [1]:
import pandas as pd
df=pd.read_csv("sales_day16.csv")
df.head()

  OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
0   O0001  27/10/23   East       C001      P008         7        653
1   O0002  25/01/23  North       C008      P010         6        690
2   O0003  29/11/24   West       C008      P006         7        433
3   O0004  21/03/24   West       C009      P008         4        984
4   O0005  22/01/23  South       C020      P002         2        850

In [17]:
#Selecting only two columns
df[["Quantity","ProductID"]].head()
#This shows that how much quantity of each product

   Quantity ProductID
0         7      P008
1         6      P010
2         7      P006
3         4      P008
4         2      P002

In [18]:
#Finds the average of UnitPrice
avg=df["UnitPrice"].mean()

In [19]:
#Displays UnitPrice greater than average of UnitPrice
fil=df[df["UnitPrice"]>avg]

In [10]:
fil

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
0     O0001  27/10/23   East       C001      P008         7        653
1     O0002  25/01/23  North       C008      P010         6        690
3     O0004  21/03/24   West       C009      P008         4        984
4     O0005  22/01/23  South       C020      P002         2        850
5     O0006  21/06/24   West       C018      P005         7        567
..      ...       ...    ...        ...       ...       ...        ...
285   O0286  25/12/23  South       C007      P001         3        563
293   O0294  15/01/23  North       C003      P003         3        622
294   O0295  09/06/24  South       C001      P008         5        884
296   O0297  31/01/24  South       C012      P007         1        647
298   O0299  27/03/23   West       C002      P006         2        763

[158 rows x 7 columns]

In [11]:
#Sort by quantity in descending order
df.sort_values(by="Quantity",ascending=False)

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
135   O0136  17/03/23   East       C005      P010        10        923
219   O0220  02/06/24   West       C004      P006        10        833
214   O0215  25/12/23   East       C016      P006        10        825
274   O0275  18/07/23   West       C016      P008        10        897
276   O0277  15/08/23   West       C019      P003        10        440
..      ...       ...    ...        ...       ...       ...        ...
290   O0291  13/03/23   West       C008      P005         1        330
239   O0240  13/06/24  South       C011      P006         1        705
242   O0243  22/09/24   East       C005      P006         1        748
22    O0023  24/09/23   East       C018      P009         1        993
17    O0018  03/02/23  South       C001      P005         1        459

[300 rows x 7 columns]

In [20]:
#Filter rows by Quantity greater than 5 and by Region North
df[(df["Quantity"]>5)& (df["Region"]=="North")]

    OrderID OrderDate Region CustomerID ProductID  Quantity  UnitPrice
1     O0002  25/01/23  North       C008      P010         6        690
12    O0013  25/11/24  North       C020      P003         6        756
14    O0015  18/03/23  North       C006      P008         6        831
27    O0028  31/08/24  North       C019      P005         8        232
38    O0039  27/03/24  North       C017      P004        10        796
43    O0044  14/01/23  North       C005      P001         6        292
47    O0048  12/11/24  North       C015      P005         6        235
48    O0049  29/11/24  North       C011      P006         9        339
60    O0061  22/08/23  North       C014      P009         8        147
72    O0073  17/09/23  North       C015      P003         8        630
74    O0075  29/06/23  North       C012      P007         6        605
90    O0091  14/12/24  North       C011      P007         7        765
92    O0093  05/07/24  North       C017      P004         8        861
100   O0101  23/10/23  North       C001      P004         8        916
101   O0102  15/09/24  North       C018      P002         8        533
114   O0115  21/09/23  North       C015      P004         6        616
136   O0137  01/11/24  North       C018      P001         6        772
143   O0144  07/10/24  North       C017      P010         8        576
156   O0157  26/08/24  North       C013      P001         6        118
159   O0160  08/02/23  North       C007      P004         9        346
163   O0164  01/02/24  North       C015      P010         7        610
164   O0165  17/05/24  North       C016      P005         6        246
177   O0178  26/09/23  North       C020      P001        10        312
187   O0188  03/10/24  North       C018      P005         7        964
198   O0199  15/04/23  North       C004      P009         8        792
201   O0202  22/12/24  North       C005      P005        10        190
202   O0203  06/03/24  North       C004      P009         7        111
212   O0213  27/02/23  North       C011      P003         6        802
218   O0219  03/08/23  North       C018      P002         9        448
231   O0232  02/10/23  North       C003      P009         7        725
252   O0253  11/08/23  North       C015      P003        10        799
256   O0257  24/09/23  North       C014      P002        10        193
266   O0267  13/10/24  North       C001      P007         8        238
280   O0281  19/07/23  North       C020      P010         8        368